# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucity" do
  version "26.10.1"

  on_macos do
    on_arm do
      sha256 "69bc95e10beea2218221bd9d4535e789d66338d9da2f87e5e3baca298ab47881"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b4370be5d218fd966d222c74904b0dcd39f195923d8ee4117f3020218dd9c06"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d304d78c979806f30509a9dd6e574474be2e20b739de71ce1d747e4b29f75de"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a438f77f826d9eced38a49096eb66e50d713f261744d6855946e974576dfb6a7"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lucity"
  desc "Deploy software on Lucity from the command line"
  homepage "https://lucity.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lucity"]
    end
  end

  # No zap stanza required
end
