# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucity" do
  version "26.9.1"

  on_macos do
    on_arm do
      sha256 "581f7d98828e41cf074f24439a967507af22b07a7876f8e35a449072874e26a5"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35c650d6b666992227b485cace97815103f9fba0faa1deb5f956a64afbee436b"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "00e407b1151dfdf84d0b370b9ec57383cbdec26b0203c23da99beeadb28fb20f"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b11f57044821a74b5d659b10587a7d6f511c078cc2cfd058ed3031b54f1173d"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lucity"
  desc "Deploy software on Lucity from the command line"
  homepage "https://lucity.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lucity"]
    end
  end

  # No zap stanza required
end
