# This file was generated by GoReleaser. DO NOT EDIT.
cask "lucity" do
  version "26.9.2"

  on_macos do
    on_arm do
      sha256 "e698fb7dcee86a44bc845fba76784ddb7d19ad6e56c61fc1512252d5b3020805"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2c31318b7b2137d6d1b604d8ddecaadb7d318be3be571a1dbf02646bfb8cd67"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cea1fa216e4a83b92fca3e92ef7ee3b01cba11be047a69552fcb52637dffa07d"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b059b59c9a324a2f9dfdc313b7bd12c952239da550f34b989cea01f6ab87dd70"
      url "https://github.com/zeitlos/lucity/releases/download/v#{version}/lucity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lucity"
  desc "Deploy software on Lucity from the command line"
  homepage "https://lucity.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lucity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lucity"]
    end
  end

  # No zap stanza required
end
