# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lucity < Formula
  desc "Deploy software on Lucity from the command line"
  homepage "https://lucity.cloud"
  version "26.7.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zeitlos/lucity/releases/download/v26.7.2/lucity_26.7.2_darwin_amd64.tar.gz"
      sha256 "a82c7faee7d4d2b17123ffe242b56987e654f0e2f5bed46c3aa81d53944faf8c"

      define_method(:install) do
        bin.install "lucity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zeitlos/lucity/releases/download/v26.7.2/lucity_26.7.2_darwin_arm64.tar.gz"
      sha256 "70bc694843f2d5931c23263767156fa1c64bf423cafacffe9c737c39f01898c5"

      define_method(:install) do
        bin.install "lucity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeitlos/lucity/releases/download/v26.7.2/lucity_26.7.2_linux_amd64.tar.gz"
      sha256 "20d9e9904f832081bf8edf6e7109596908e171612e3259f5581b5f2ca48fad9f"
      define_method(:install) do
        bin.install "lucity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeitlos/lucity/releases/download/v26.7.2/lucity_26.7.2_linux_arm64.tar.gz"
      sha256 "df410982dfa5edfe1de81b266788b399a179644c711af221d6e901f30d32f5cc"
      define_method(:install) do
        bin.install "lucity"
      end
    end
  end

  test do
    assert_match "lucity", shell_output("#{bin}/lucity version")
  end
end
